# Generated by Django 5.2.6 on 2025-09-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('año', models.DateTimeField(auto_now_add=True)),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
    ]
